-- MySQL Script generated by MySQL Workbench
-- Thu Feb  8 12:42:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

--
-- Table `melis_site_translation`
--
DROP TABLE IF EXISTS `melis_site_translation` ;

CREATE TABLE IF NOT EXISTS `melis_site_translation` (
  `mst_id` int(11) NOT NULL AUTO_INCREMENT,
  `mst_site_id` int(11) NOT NULL,
  `mst_key` varchar(255) NOT NULL,
  PRIMARY KEY (`mst_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `melis_site_translation_text`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_site_translation_text` ;

CREATE TABLE IF NOT EXISTS `melis_site_translation_text` (
  `mstt_id` int(11) NOT NULL AUTO_INCREMENT,
  `mstt_mst_id` int(11) NOT NULL,
  `mstt_lang_id` int(11) NOT NULL,
  `mstt_text` text NOT NULL,
  PRIMARY KEY (`mstt_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


