-- MySQL Script generated by MySQL Workbench
-- 06/21/16 06:58:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema melisv2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `melis_cms_page_tree`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_cms_page_tree` ;

CREATE TABLE IF NOT EXISTS `melis_cms_page_tree` (
  `tree_page_id` INT(11) NOT NULL COMMENT '',
  `tree_father_page_id` INT(11) NOT NULL DEFAULT '-1' COMMENT '',
  `tree_page_order` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`tree_page_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = 'List of Melis pages, and their parents';


-- -----------------------------------------------------
-- Table `melis_cms_lang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_cms_lang` ;

CREATE TABLE IF NOT EXISTS `melis_cms_lang` (
  `lang_cms_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `lang_cms_locale` VARCHAR(10) NOT NULL COMMENT '',
  `lang_cms_name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`lang_cms_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melis_cms_page_lang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_cms_page_lang` ;

CREATE TABLE IF NOT EXISTS `melis_cms_page_lang` (
  `plang_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `plang_page_id` INT(11) NOT NULL COMMENT '',
  `plang_lang_id` INT(11) NOT NULL COMMENT '',
  `plang_page_id_initial` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`plang_id`)  COMMENT '',
  INDEX `lang_page_id_idx` (`plang_page_id` ASC)  COMMENT '',
  INDEX `lang_page_id_initial_idx` (`plang_page_id_initial` ASC)  COMMENT '',
  INDEX `lang_lang_id_idx` (`plang_lang_id` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = 'Relation between pages and lang';


-- -----------------------------------------------------
-- Table `melis_cms_site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_cms_site` ;

CREATE TABLE IF NOT EXISTS `melis_cms_site` (
  `site_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `site_name` VARCHAR(45) NOT NULL COMMENT '',
  `site_main_page_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`site_id`)  COMMENT '',
  INDEX `site_main_page_id_idx` (`site_main_page_id` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = 'List of melis websites declared';


-- -----------------------------------------------------
-- Table `melis_cms_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_cms_template` ;

CREATE TABLE IF NOT EXISTS `melis_cms_template` (
  `tpl_id` INT(11) NOT NULL COMMENT '',
  `tpl_site_id` INT(11) NOT NULL COMMENT '',
  `tpl_name` VARCHAR(255) NOT NULL COMMENT '',
  `tpl_type` ENUM('PHP','ZF2') NOT NULL DEFAULT 'ZF2' COMMENT '',
  `tpl_zf2_website_folder` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `tpl_zf2_layout` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `tpl_zf2_controller` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `tpl_zf2_action` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `tpl_php_path` VARCHAR(150) NULL DEFAULT NULL COMMENT '',
  `tpl_creation_date` DATETIME NULL COMMENT '',
  `tpl_last_user_id` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`tpl_id`)  COMMENT '',
  INDEX `tpl_site_id_idx` (`tpl_site_id` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'List of Melis Templates used by the pages';


-- -----------------------------------------------------
-- Table `melis_cms_page_published`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_cms_page_published` ;

CREATE TABLE IF NOT EXISTS `melis_cms_page_published` (
  `page_id` INT(11) NOT NULL COMMENT '',
  `page_type` ENUM('SITE','FOLDER','PAGE') NOT NULL DEFAULT 'PAGE' COMMENT '',
  `page_status` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '',
  `page_menu` ENUM('LINK','NOLINK','NONE') NOT NULL DEFAULT 'LINK' COMMENT '',
  `page_name` VARCHAR(255) NOT NULL COMMENT '',
  `page_tpl_id` INT(11) NOT NULL COMMENT '',
  `page_content` LONGTEXT NULL DEFAULT NULL COMMENT '',
  `page_taxonomy` TEXT NULL COMMENT '',
  `page_creation_date` DATETIME NULL DEFAULT NULL COMMENT '',
  `page_edit_date` DATETIME NULL DEFAULT NULL COMMENT '',
  `page_last_user_id` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`page_id`)  COMMENT '',
  INDEX `pub_page_tpl_id_idx` (`page_tpl_id` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = 'List of published pages';


-- -----------------------------------------------------
-- Table `melis_cms_page_saved`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_cms_page_saved` ;

CREATE TABLE IF NOT EXISTS `melis_cms_page_saved` (
  `page_id` INT(11) NOT NULL COMMENT '',
  `page_type` ENUM('SITE','FOLDER','PAGE') NOT NULL DEFAULT 'PAGE' COMMENT '',
  `page_status` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '',
  `page_menu` ENUM('LINK','NOLINK','NONE') NOT NULL DEFAULT 'LINK' COMMENT '',
  `page_name` VARCHAR(255) NOT NULL COMMENT '',
  `page_tpl_id` INT(11) NOT NULL COMMENT '',
  `page_content` LONGTEXT NULL DEFAULT NULL COMMENT '',
  `page_taxonomy` TEXT NULL COMMENT '',
  `page_creation_date` DATETIME NULL COMMENT '',
  `page_edit_date` DATETIME NULL COMMENT '',
  `page_last_user_id` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`page_id`)  COMMENT '',
  INDEX `save_page_tpl_id_idx` (`page_tpl_id` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = 'List of saved pages';


-- -----------------------------------------------------
-- Table `melis_cms_page_seo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_cms_page_seo` ;

CREATE TABLE IF NOT EXISTS `melis_cms_page_seo` (
  `pseo_id` INT(11) NOT NULL COMMENT '',
  `pseo_url` VARCHAR(255) NULL COMMENT '',
  `pseo_url_redirect` VARCHAR(255) NULL COMMENT '',
  `pseo_url_301` VARCHAR(255) NULL COMMENT '',
  `pseo_meta_title` VARCHAR(255) NULL COMMENT '',
  `pseo_meta_description` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`pseo_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = 'SEO datas for pages';


-- -----------------------------------------------------
-- Table `melis_cms_platform_ids`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_cms_platform_ids` ;

CREATE TABLE IF NOT EXISTS `melis_cms_platform_ids` (
  `pids_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `pids_page_id_start` INT(11) NOT NULL COMMENT '',
  `pids_page_id_current` INT(11) NOT NULL COMMENT '',
  `pids_page_id_end` INT(11) NOT NULL COMMENT '',
  `pids_tpl_id_start` INT(11) NOT NULL COMMENT '',
  `pids_tpl_id_current` INT(11) NOT NULL COMMENT '',
  `pids_tpl_id_end` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`pids_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = 'Saves ids intervals for each environment so that no duplicate id can occur between platforms';


-- -----------------------------------------------------
-- Table `melis_cms_site_404`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_cms_site_404` ;

CREATE TABLE IF NOT EXISTS `melis_cms_site_404` (
  `s404_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `s404_site_id` INT(11) NOT NULL COMMENT '',
  `s404_page_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`s404_id`)  COMMENT '',
  INDEX `404_site_id_idx` (`s404_site_id` ASC)  COMMENT '',
  INDEX `404_page_id_idx` (`s404_page_id` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = 'List of 404 pages per site';


-- -----------------------------------------------------
-- Table `melis_cms_site_domain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_cms_site_domain` ;

CREATE TABLE IF NOT EXISTS `melis_cms_site_domain` (
  `sdom_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `sdom_site_id` INT(11) NOT NULL COMMENT '',
  `sdom_env` VARCHAR(50) NOT NULL COMMENT '',
  `sdom_scheme` VARCHAR(10) NOT NULL COMMENT '',
  `sdom_domain` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`sdom_id`)  COMMENT '',
  INDEX `dom_site_id_idx` (`sdom_site_id` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = 'List of domains per site and per environments';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



