-- MySQL Script generated by MySQL Workbench
-- 06/21/16 07:00:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Data for table `melisv2`.`melis_cms_lang`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `melis_cms_lang` (`lang_cms_id`, `lang_cms_locale`, `lang_cms_name`) VALUES (1, 'en_EN', 'English');
INSERT INTO `melis_cms_lang` (`lang_cms_id`, `lang_cms_locale`, `lang_cms_name`) VALUES (2, 'fr_FR', 'Français');

COMMIT;


-- -----------------------------------------------------
-- Data for table `melisv2`.`melis_cms_site_404`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `melis_cms_site_404` (`s404_id`, `s404_site_id`, `s404_page_id`) VALUES (1, -1, 1);

COMMIT;

